[package]
name = "cartridge-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
[dependencies]
cartridge-core.workspace = true
serde_json.workspace = true
ctrlc = { version = "3", features = ["termination"] }
